language: node_js
node_js:
  - '12.18.3'
git:
  depth: false
cache:
  npm: true
  directories:
    - $HOME/.cache/pre-commit
addons:
  - sonarcloud:
    organization: 'rgposadas'
    token:
      secure: $SONAR_TOKEN

before_script:
  - pyenv global 3.7.1
  - pip3 install pre-commit

script:
  - pre-commit run -a
  - ./scripts/ci-checks.sh
  - sonar-scanner
