language: node_js
node_js:
  - '12.18.3'
git:
  depth: false
cache:
  npm: true
  directories:
    - $HOME/.cache/pre-commit
before_script:
  - pyenv global 3.7.1
  - pip3 install pre-commit
addons:
  - sonarcloud:
    organization: 'rgposadas'
    token:
      secure: $SONAR_TOKEN
script:
  - pre-commit run -a
  - npm run affected:lint -- --base=origin/master
  - npm run affected:test -- --base=origin/master --codeCoverage
  - npm run affected:e2e -- --base=origin/master
  - sonar-scanner
