apiVersion: v1
kind: Namespace
metadata:
  name: litterrally-prod
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: litterrally-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/RGPosadas/LitterRally.git
    targetRevision: setup-ci-cd
    path: k8s/kustomize/env/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: litterrally-prod
