# This manifest is reponsible for deploying our frontend.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mull-frontend
  namespace: mull
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mull-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mull-frontend
    spec:
      containers:
        - name: mull-frontend
          image: 'ritchellegmp/mull-frontend:usability-testing-release-3'
          imagePullPolicy: Always
          ports:
            - name: frontend
              containerPort: 4200
              protocol: TCP
