# This manifest is responsible for using cert-manager to provision our domain's
# SSL certificate using LetsEncrypt as a Certificate Authority (in-cluster known as ClusterIssuer).
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: ritchelle.posadas@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx
